### ISSUE TITLE
Provide a way to exclude based on filetype

### ISSUE THREAD

**Issue by elyscape** [editorconfig/editorconfig-vim#104]
`g:EditorConfig_exclude_patterns` is useful, but it would be really nice if there were a way to disable EditorConfig based on filetype. As an example, if I want to disable EditorConfig for git commit messages, I currently have to add a pattern like `.*\.git[\\/].*EDITMSG` to the exclude patterns. If I could instead exclude based on filetype, I could just blacklist the `gitcommit` filetype (or, to go even further, `git.*`).

**Comment by xuhdev** [comment]
@elyscape Since these settings are really arbitrary, I suggest you to look into `editorconfig-hook`. `g:EditorConfig_exclude_patterns` was added before hook was implemented (and was useful).

**Comment by elyscape** [comment]
Ooh, nice. That should probably be documented in the README.

**Comment by elyscape** [comment]
Doing some digging, I don't think I'll be able to use `editorconfig-hook`. It's run [at the end of `s:ApplyConfig()`][ApplyConfig], after all the settings changes are already applied. I need something that will run before any are made.

[ApplyConfig]: https://github.com/editorconfig/editorconfig-vim/blob/0abb0634a8bf3c760a283e9e7475594b83869a46/plugin/editorconfig.vim#L658

**Comment by mbyio** [comment]
For another datapoint, there are some file types where it doesn't make sense to use editorconfig. For example, Go uses an automatic formatter, so the indent style used by the editor is always overwritten anyway. In that case editorconfig just messes with someone's preferred settings for no reason.

**Comment by cxw42** [comment]
Now that #154 has been merged, you can set up an autocmd in your .vimrc:

    au FileType gitcommit let b:EditorConfig_disable = 1

(needs commit 8f6eba5fd6c306e0480ea72917902a2bde162d73 or newer).  Feel free to reopen if you have any issues.  Thanks!
