### ISSUE TITLE
Python deprecation

### ISSUE THREAD

**Issue by mvitz** [editorconfig/editorconfig-vim#108]
Hi. I'm not sure if this is this plugins problem or a general VIM problem.

I'm running VIM 8.1-100 on macOS High Sierra with Python 3.7.0. Every time I open a file the following deprecation is printed:

```
Error detected while processing function <SNR>17_UseConfigFiles[26]..<SNR>17_Initialize[47]..<SNR>17_InitializePythonBuiltin:
line   23:
/must>not&exist/foo:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
```

If I remove editorconfig-vim no deprecation is printed and everything works as expected.

**Comment by k-takata** [comment]
This is a Vim issue: vim/vim#3117

**Comment by xuhdev** [comment]
To circumvent, I think you can enable either Python 2 or 3, but not both.
