### ISSUE TITLE
Rules defined for filenames with a leading . are not loaded

### ISSUE THREAD

**Issue by iamFIREcracker** [editorconfig/editorconfig-vim#114]
Rules defined for filenames with a leading `.` are not loaded up by the plugin.

My .editorconfig:
```
[*]
indent_size = 2
tab_width = 2

[.vimrc]
indent_size = 4
tab_width = 4
```

When I edit my .vimrc file, and run `verbose set shiftwidth` I get the following:

```
  shiftwidth=2
        Last set from ~/my-env/dotfiles/.vim/pack/bundle/start/vim-editorconfig/autoload/editorconfig/indent_size.vim line 16
```

With the following .editorconfig instead (no more `.`):
```
[*]
indent_size = 2
tab_width = 2

[vimrc]
indent_size = 4
tab_width = 4
```
settings are loaded up just fine:

```
  shiftwidth=4
        Last set from ~/my-env/dotfiles/.vim/pack/bundle/start/vim-editorconfig/autoload/editorconfig/indent_size.vim line 16
```

Is this expected?

**Comment by xuhdev** [comment]
What's your value of `g:EditorConfig_core_mode`?

**Comment by iamFIREcracker** [comment]
Apologies @xuhdev, but I did not see your reply...

...and even bigger apologies, I did not realize I filed this to the wrong project: editorconfig-vim vs vim-editorconfig...
