### ISSUE TITLE
editorconfig ignores patterns

### ISSUE THREAD

**Issue by vvvvv** [editorconfig/editorconfig-vim#118]
editorconfig-vim seems to be ignoring the [\*.go] directives.  
With the following vimrc and editorconfig my go files only get indeted by 2 spaces.  
It seems to be ignoring anything apart from the [\*] directive 

### .vimrc
```
filetype indent plugin on
call plug#begin('~/.vim/plugged')"
Plug 'editorconfig/editorconfig-vim'
call plug#end()
```

### .editorconfig
```
# http://editorconfig.org/

root = true

###########################################################
; common
###########################################################

[*]
charset = utf-8
end_of_line = LF
insert_final_newline = true
trim_trailing_whitespace = true
indent_style = space
indent_size = 2

[*.go]
indent_style = tab
ident_size = 8
```

**Comment by xuhdev** [comment]
You have a typo `ident_size`

**Comment by vvvvv** [comment]
holy fuck I can't believe I've spent 2 hours trying to debug this. 
FML thanks a bunch and sorry for my idiocy
