### ISSUE TITLE
Non-beta release

### ISSUE THREAD

**Issue by dvzrv** [editorconfig/editorconfig-vim#143]
Hi! I would like to package this plugin for Arch Linux.

However, we have [a policy about package versioning](https://wiki.archlinux.org/index.php/Arch_package_guidelines#Package_versioning), that states to not (at least not without any good reason such as deprecation of frameworks on a distribution level or bug fixes that are not ported trivially) bring in alpha or beta releases into the repositories.

Is there a plan for a new stable release, given that the last one has been done in 2015(!)?

Thanks!

**Comment by cxw42** [comment]
Thanks for asking!  I think we should be able to do that.  There's an open question about versioning I'll have to track down, but other than that I haven't received any reports that I consider blockers.  Do you need anything from us other than a tag on the relevant commit?

**Comment by dvzrv** [comment]
@cxw42 Thanks for getting back to me so quickly!

> Do you need anything from us other than a tag on the relevant commit?

If you are able to do PGP signed commits and or release tarballs and also clarify who is authorized "release person" for this repository (to be able to check detached signatures against a public key), that would be ace (but it's not required of course).

Other than that I'm still on integrating the ruby vimrunner based test suite (always good to run some tests on everything :) ) but am using this plugin as a system-wide vim plugin successfully while writing this!

**Comment by cxw42** [comment]
@xuhdev I have access to the "Draft a new release" button, so I think I should be able to.  Do we have any project store of PGP pubkeys?

**Comment by cxw42** [comment]
Versioning vote in progress at editorconfig/editorconfig-vote/issues/11

**Comment by dvzrv** [comment]
Nice, thank you! Looking forward :)

**Comment by dvzrv** [comment]
Is there something missing or something that can be helped with? It would be awesome to be able to package this! :)

**Comment by cxw42** [comment]
Thanks for asking!  We're working through the spec changes re. versioning so I can bump this and still pass the tests :) .  I appreciate your patience!

**Comment by cxw42** [comment]
Still waiting - I just sent a ping in the spec PR

**Comment by cxw42** [comment]
Versioning proceeding --- we now have semver for the specification, which is a big step forward!

**Comment by cxw42** [comment]
PR open --- once the CI passes, I can cut the release!  

@xuhdev Do we have any project store of PGP pubkeys?  Or is the GitHub "verified" flag on a release sufficient authorization?

**Comment by cxw42** [comment]
https://github.com/editorconfig/editorconfig-vim/releases/tag/v1.1.1 \o/

@dvzrv let me know if you need anything else!  I can always add a signed tag later if necessary.  Let me know if you have any issues.

Would you please close this issue once editorconfig-vim is packaged?  I would also appreciate a PR  with the Arch installation instructions if you would be willing.

Thank you again for your support of EditorConfig!

**Comment by rmedaer** [comment]
Hi guys,

I'm going to do a new release of the Debian package as well. Already discussed with the previous/original maintainers.

Kind regards,

**Comment by cxw42** [comment]
@dvzrv Thanks - I see https://www.archlinux.org/packages/community/any/vim-editorconfig/ is up! :+1: Closing this issue.

@rmedaer Were you able to get a new .deb packaged?  I see that [bionic](https://packages.ubuntu.com/bionic/vim-editorconfig) and [focal](https://packages.ubuntu.com/focal/vim-editorconfig) have not been updated in the mainline, but I don't know if you have a PPA or something.  Much appreciated!
