### ISSUE TITLE
Consider preserving user's colorcolum setting?

### ISSUE THREAD

**Issue by knghtbrd** [editorconfig/editorconfig-vim#158]
Could we maybe set colorcolumn+= rather than colorcolumn= when max_line_length is set? I have other uses for mine besides marking a margin line.

**Comment by cxw42** [comment]
Sounds reasonable to me --- pull requests welcome! :)

**Comment by avahe-kellenberger** [comment]
Yes, please. This is very strange to see

**Comment by xuhdev** [comment]
Could you explain what this is for?

**Comment by kmoschcau** [comment]
I just ran into this as well. Another thing you might want to consider is to not set it to a hard value, but to set it to `+1` instead. This will just set the colorcolumn to one column further than `'textwidth'` has already been set.

**Comment by cxw42** [comment]
Fixed by #164
