### ISSUE TITLE
Plugin doesn't catch files with shebang on first run

### ISSUE THREAD

**Issue by alerque** [editorconfig/editorconfig-vim#165]
I have some shell scripts without extensions. I've added a project level Editor Config file that calls these out by exact name and sets the indent style. The trouble is these settings are not applied when opening a file from the terminal:

`.editorconfig`
```ini
[myfile]
indent_style = tab
```

`myfile`
```sh
#!/bin/sh
echo
```

Opened with...

```console
$ nvim myfile
```

...the indent style will be spaces because the shebang based file type detection ran *after* anything this plugin did. I can then run `:e %` to reload the buffer, and now the editorconfig settings are applied. The same is also true if launching with no file, then opening the file.

The problem also goes away if the shebang line is removed, i.e. the EditorConfig settings are properly applied to such files if the shebang doesn't interfere.

**Comment by cxw42** [comment]
Thanks for reporting!  
- Does this happen with vanilla Vim?
- What OS and version?
- What Neovim version?
I know there are a number of open issues related to interactions of this type.

**Comment by alerque** [comment]
I don't usually use vanilla vim for anything so don't have a working config, but running this suggests that it works out of the box on vanilla vim:

```console
$ vim -N -u <(cat << EOF
filetype off
set rtp+=/home/caleb/.config/nvim/plugged/editorconfig-vim
filetype plugin indent on
syntax enable
EOF
) vcsh
```

Of course `vcsh` is the script I'm trying to edit and the `$PWD` has an `.editorconfig` with my settings. It seems to be loading on first open, although I'm confused now because the same test with NeoVIM seem to work too:

```console
$ nvim -u <(cat << EOF
filetype off
set rtp+=/home/caleb/.config/nvim/plugged/editorconfig-vim
filetype plugin indent on
syntax enable
EOF
) vcsh
```

I'll have to sort through my other plugins to see if something is interfering.

**Comment by cxw42** [comment]
Let us know what you find!

**Comment by alerque** [comment]
This actually traces to use in combination with [vim-stdtabs](https://github.com/sdanielf/vim-stdtabs). I'll close this issue because it looks like that plugin is doing the hijacking and this one does work on it's own and in combination with the 106 other plugins I use.

Similar answers might apply to other folks with similar problems. If not that plugin perhaps others or their own configs that do similar things blindly setting values for file types.

**Comment by cxw42** [comment]
Thanks for checking and for letting us know!  106 is a lot :) .
