### ISSUE TITLE
Error detected whiile processing function<SNR>28_UseConfigFiles

### ISSUE THREAD

**Issue by dagadbm** [editorconfig/editorconfig-vim#167]
I had  to uninstall your plugin because I always  get this error everytime  i open a buffer:

Error detected whiile processing function<SNR>28_UseConfigFiles:
line 40:
E714: list required

I  am using neovim nightly together  with  native LSP and packer.

**Comment by dagadbm** [comment]
I do not  really know why this  happens but uninstalling your plugin stoped the  error.

**Comment by cxw42** [comment]
Thanks for reporting!  What plugin version, neovim version, OS version?

**Comment by k-takata** [comment]
This might happen if you set a wrong value to `g:EditorConfig_exclude_patterns`.

**Comment by dagadbm** [comment]
Hey!

I am using macOS 11.2.1 (Big Sur)
Plugin  version Im  sure its the latest from the time of this writing
because i update everything regularly
Neo vim version is:

NVIM v0.5.0-dev+48e805728
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall
-Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99
-Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla
-fstack-protector-strong -fno-common -fdiagnostics-color=auto
-DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32
-DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3
-I/tmp/neovim-20210407-66517-1uj5620/build/config
-I/tmp/neovim-20210407-66517-1uj5620/src -I/usr/local/include
-I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
-I/usr/local/opt/gettext/include
-I/tmp/neovim-20210407-66517-1uj5620/build/src/nvim/auto
-I/tmp/neovim-20210407-66517-1uj5620/build/include

using brew update neovim --fetch-HEAD (or something)

Oh  on the  editor config exclude pattern.. you are actually right!

I  am using this:
-- EditorConfig
vim.g.EditorConfig_exclude_patterns = 'fugitive://.*'

On a .lua  file. som maybe i just cannot use this regular string like this?
Any  ideas?

**Comment by dagadbm** [comment]
i fixed  it. thank you so much!

now i just need to  fix all the other hundreds o f issues i have with
stupid native LSP.

Here is the solution:

vim.g.EditorConfig_exclude_patterns = { [[fugitive://.*]] }

or

vim.g.EditorConfig_exclude_patterns = { 'fugitive://.*' }

for people using lua. if  you are using vimscript just do ['fugitive://.*']

**Comment by cxw42** [comment]
@k-takata 👍 

@dagadbm Thank you for sharing your version info and the fix!
