### ISSUE TITLE
editorconfig-vim does not work when used along side file-line plugin

### ISSUE THREAD

**Issue by sidcha** [editorconfig/editorconfig-vim#169]
I'm using editorconfig-vim and [file-line](https://github.com/bogado/file-line) plugins together and they don't play nice.
```
vim filename.c      # Respects .editorconfig settings
vim filename.c:23   # Uses defaults
```
Creating an issue here as I think this could be due to filetype detection issue. ie., editorconfig-vim sees `c:23` as filetype and hence the rules don't apply.

PS: file-line plugin is great as it allows me to copy-paste sections of text from of `grep -rn` or `git grep -n` and jump to the line in file without having to `s/:/ +/` on that section. So I'd love to keep both of these plugins.

**Comment by cxw42** [comment]
Thanks for reporting!  What platform, OS version, Vim flavor and version, and plugin versions?

**Comment by cbsiddharth** [comment]
OS: Ubuntu 18.04.5 LTS (Bionic Beaver)
Vim - from apt; 8.0 (Included patches: 1-1453)
editorconfig-vim: git master
file-line: git master

**Comment by cxw42** [comment]
Thanks for the info, and sorry for the delay in responding!  file-line seems to break a number of plugins :( .

https://github.com/bogado/file-line/pull/77 claims to fix some plugins --- could you try with the code from that PR and see if it fixes the problem?

**Comment by sidcha** [comment]
I switched to using https://github.com/wsdjeg/vim-fetch which works with this plugin and is a drop-in replacement for file-line.

**Comment by cxw42** [comment]
Great to hear --- thanks for letting us know the fix!
