### ISSUE TITLE
compiled python files should be ignored by git

### ISSUE THREAD

**Issue by mlippert** [editorconfig/editorconfig-vim#219]
## Description
I have editorconfig-vim as a submodule for my personal vim config git repository. It is in `vim/pack/my/start/editorconfig-vim`.

When I look at untracked files, I see all of `editorconfig-vim/plugin/editorconfig-core-py/editorconfig/__pycache__/*.pyc` files.

Since cached compiled python shouldn't be committed, I think it would be best to add them to the `.gitignore` file at the root of the editorconfig-vim repository.

## Solution
Adding this to the `.gitignore` should do it:
```
# ignore cached compiled (*.pyc) python files
__pycache__/
```

**Comment by cxw42** [comment]
PRs welcome!

**Comment by mlippert** [comment]
sure I'll submit one, gotta fork the repo first, so give me a bit.

**Comment by mlippert** [comment]
Well I was about to create a PR (and I still will if you want) but I discovered that the *.pyc files in my vim/pack were just left behind files from an old (very old) version of the plugin.

It seems that commit [37bedf88](https://github.com/editorconfig/editorconfig-vim/commit/37bedf88cabb61d4580295b6e347058df7e7f1b4) "fixed" the issue by removing the files that were being compiled.

So a PR to update the `.gitignore` as I suggesting would be useful only if python code that needs to be compiled is added to the repo again.

This issue can be closed.

**Comment by cxw42** [comment]
OK --- thanks!
