### ISSUE TITLE
submit to vim

### ISSUE THREAD

**Issue by chrisbra** [editorconfig/editorconfig-vim#223]
Hi, 
I am sure you are aware of https://github.com/vim/vim/issues/2286
I am now considering to include it for the upcoming Vim 9.1 release and just wanted to check with you, whether you are okay with this?
Also, just in case there are any major blockers in the master branch, that should be fixed before distributing this with Vim?

Thanks,
Chris

**Comment by xuhdev** [comment]
Hi Chris,

I have no problem in including it in Vim. I don't see any major blocks either.

I'm not sure how Vim's development model is gonna change. If possible, I'm ok with developing it as part of Vim.

Also, let's hear what other developers say. @cxw42

Let me know what you think.
Hong

**Comment by cxw42** [comment]
@chrisbra Thanks for the consideration!  No blockers except #221, which sounds like it's a one-line fix.

> development model

- Would we continue developing the plug-in here,  or would issues and PRs need to go in vim itself?
- I'd like to keep the plug-in compatible with earlier Vims, so would rather not fork off a vim9script version.  Is that OK, or would we have to have a 9script version in Vim 9.1?
- Do you have any particular versioning requirements for plugins distributed with Vim 9.1?  E.g., do you want strict semver or anything like that?

Thanks again!  I am very excited to see this plug-in distributed with the (world's greatest :) ) editor!

**Comment by chrisbra** [comment]
Should be fine. I'd appreciate, if it would be continued to be maintained here. There is no hurry to change it to Vim9 script in my opinion (unless there are real gains here). The only other issue, you may want to consider at one point is that apparently it is not correctly auto-loaded (e.g. even when not used, it is loaded.). Not sure how bad this is, but I'll make it an optional plugin anyhow, so this may not be so bad.

**Comment by cxw42** [comment]
Sure,  and actually I just opened #222 the other day to use autoload more effectively.

**Comment by chrisbra** [comment]
closing as of Vim Commit https://github.com/vim/vim/commit/e5e04306bf02aa4ad488558dd593cf5c3b72f9b7

**Comment by cxw42** [comment]
I tagged https://github.com/editorconfig/editorconfig-vim/releases/tag/v.1.2.1-alpha.1 to record where Vim first pulled in the plugin.  I used a pre-release tag since the plugin at that commit suffers from #224.  (Sorry about that!  It is an ergonomics issue, not functionality.)
