### ISSUE TITLE
shift width ignored 

### ISSUE THREAD

**Issue by mhowellj** [editorconfig/editorconfig-vim#231]
as of commit 7eec46701ec7a954a6cb0b0e348ad7c13a893425 the .editorconfig shift width setting no longer takes effect 

I'm running MacVim r178 (Vim 9.0.1897). I usually open files from iTerm2 but I also tried opening from the Finder i case iTerm2 was the problem. 

Checking out the previous commit fixed the issue.

With the problematic commit, 
:verbose set sw? returned "Last set from .gvimrc" 
whereas :verbose set expand tab? was last set from editorconfig.vim

my .editorconfig (I was opening a .py file):

```
# EditorConfig is awesome: https://EditorConfig.org

# top-most EditorConfig file
root = false

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true

# 4 space indentation
[*.py]
charset = utf-8
indent_style=space
indent_size=4
tab_width=4
```

**Comment by xuhdev** [comment]
This is being fixed at https://github.com/editorconfig/editorconfig-vim/pull/230

**Comment by xuhdev** [comment]
Dup of #232 (use #232 to track for deeper discussion there)
