### ISSUE TITLE
l:bufnr seems undefined

### ISSUE THREAD

**Issue by nedbat** [editorconfig/editorconfig-vim#232]
I noticed trailing spaces weren't being trimmed anymore.  Debugging through the plugin, execution seemed to stop on line 458:
https://github.com/editorconfig/editorconfig-vim/blob/master/plugin/editorconfig.vim#L458-L464

That code was changed in https://github.com/editorconfig/editorconfig-vim/commit/7eec46701ec7a954a6cb0b0e348ad7c13a893425.

I added some debugging:
```vim
    echo 'l:'
    echo l:
    if s:IsRuleActive('tab_width', a:config) && bufname(l:bufnr) !~# '^!\w*sh$'
```
and I see this:
```
l:
{}
```
I don't know why `l:bufnr` isn't defined, but it's stopping the plugin from working.

**Comment by nedbat** [comment]
I think in this line:
```vim
    if s:IsRuleActive('tab_width', a:config) && bufname(l:bufnr) !~# '^!\w*sh$'
```
you want `a:bufnr` not `l:bufnr`.

**Comment by xuhdev** [comment]
This is being fixed in https://github.com/editorconfig/editorconfig-vim/pull/230

**Comment by xuhdev** [comment]
Do you have any reference to `a:bufnr`? It seems to be working but I couldn't find any official references to it.

**Comment by xuhdev** [comment]
Fixed by https://github.com/editorconfig/editorconfig-vim/pull/230
