### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by marr** [editorconfig/editorconfig-vim#25]
Hi, I have macvim (-python) and I can't seem to get this plugin to work. I built editorconfig with `brew install editorconfig` and cloned this repo into my ~/.vim/bundle (loading with pathogen).
My ~/.editorconfig looks like:

```
[{package.json,.travis.yml}]
indent_style = space
indent_size = 2
```

And I still see vim trying to use 4 space; my .vimrc has this setting for tabstop, softtabstop and shiftwidth.

**Comment by xuhdev** [comment]
It should work in this case, but we can do some troubleshooting first:

- Do you have `editorconfig` command in $PATH? You can run `which editorconfig` to verify it.
- What is the output of `editorconfig /path/to/some/package.json`? Maybe there is a project `.editorconfig` which has specified `root = true` to avoid polluted by personal `.editorconfig` files.

**Comment by marr** [comment]
Ah great, it was the second thing. I forgot my project actually had a .editorconfig in it too. And yes it had set root = true. Thanks for your help!
