### ISSUE TITLE
global configuration not working

### ISSUE THREAD

**Issue by rashivkp** [editorconfig/editorconfig-vim#26]
in my ~/.editorconfig file, it contains this

[*]
end_of_line = LF
charset = utf-8
indent_size = 4
indent_style = space
trim_trailing_whitespace = true

when opening vim to create a new file without extensions, it doesn't follow the configurations defined.

**Comment by xuhdev** [comment]
Do you have a project `.editorconfig` file which contains the line `root = true`? If it contains this line, the project would have project specific settings which causes editorconfig to ignore any `.editorconfig` files in upper level directories.

**Comment by rashivkp** [comment]
the specific configuration in projects works fine.  here what I am doing

$ git init repo
$ cd repo
$ vim

then the editor doesn't follow the default configuration defined in ~/.editorconfig file.

**Comment by xuhdev** [comment]
@rashivkp Yes, it is expected. If you use Vim to create a new buffer, EditorConfig won't know the path of this file. Does it make sense?

**Comment by rashivkp** [comment]
yes it make sense. when I tried to create new file with 
```
:tabe filename    or 
$ vim filename
```
it works as expected
