### ISSUE TITLE
Error when used with fugitive

### ISSUE THREAD

**Issue by whitneyit** [editorconfig/editorconfig-vim#28]
I'm using the [`vim-fugitive`](https://github.com/tpope/vim-fugitive) plugin in combination with `editorconfig-vim` and when I `:Gblame` and try to view the git commit Object I receive the following error:

> Error detected while processing function <SNR>30_UseConfigFiles.. SNR>30_UseConfigFiles_Python_Builtin:
> line   23:
> Input file must be a full path name.

I have tracked the error down to [plugin/editorconfig-core-py/editorconfig/handler.py#L92](https://github.com/editorconfig/editorconfig-vim/blob/f657c85356a30e1dca078c4ccc218c852842996b/plugin/editorconfig-core-py/editorconfig/handler.py#L92).

It appears that fugitive is passing the following as the `filepath`:

> fugitive:///home/vagrant/Code/dotfiles/.git/a6f75e74cb68bd42d9e459c63f1c2c01b75a05a6

Would it be possible to just ignore files that begin with the *fugitive protocol*, or be able to specify a pattern of files to ignore?

**Comment by xuhdev** [comment]
See editorconfig/editorconfig#200

**Comment by whitneyit** [comment]
Thanks for the link. Worked like a charm :smile:

Do you want a PR to add this to the Readme?

**Comment by xuhdev** [comment]
@whitneyit Thanks! I would appreciate if you can make the PR

**Comment by xuhdev** [comment]
I think it's better to add a faq section in the doc, then link to the doc from the README file

**Comment by whitneyit** [comment]
I wasn't planning on doing a faq section since I only have asked one question. I was just gonna give a brief overview of the settings and then a simple *Recommended Options* section
