### ISSUE TITLE
max_line_length does not wrap lines when formatoptions is set 'incorrectly'

### ISSUE THREAD

**Issue by jgkamat** [editorconfig/editorconfig-vim#30]
When max_line_length is set to some value, it only wraps lines when formatoptions is set with at least "tc". Some filetypes don't have these set by default, but this leads to the option 'not working' when formatoptions isn't set correctly (for these types of files, like java files).

'fixing' this would be trivial, just appending "tc" to formatoptions fixes the problem, by forcing line wrap in both comments and normal text, but should this be default? I personally think it should, as that is what I am looking for when I have that option set. [The editorconfig properties also imply this](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties), but I'm not sure if this should be changed.

If people decide this should be done, I would be happy to do it, it should be a small change. Let me know what you think!

**Comment by xuhdev** [comment]
Yes, I think this should be done. it can be done by modifying a buffer local formatoption value.

**Comment by jgkamat** [comment]
b173a39 looks good so far, I'm going to test it and submit a pull request tomorrow. I couldn't figure out how to get it to work without setlocal, but that seems to be working fine for multiple panes/buffers/splits/tabs.

**Comment by xuhdev** [comment]
@jgkamat I can't see any problem using `setlocal`, would you mind telling your concern?

**Comment by jgkamat** [comment]
I just saw `let &l:<xx>` being used everywhere else, and I thought it was against the style guide. I don't see any actual problems with using setlocal.

**Comment by xuhdev** [comment]
It's OK. When rvalue is a literal constant, it is cleaner to use setlocal.
