### ISSUE TITLE
vim-pathogen support

### ISSUE THREAD

**Issue by hoxu** [editorconfig/editorconfig-vim#33]
Please support [vim-pathogen](https://github.com/tpope/vim-pathogen) as an installation method.

**Comment by xuhdev** [comment]
What kind of support do you expect? Pathogen does not need plugins to support. (I use pathogen myself.)

**Comment by hoxu** [comment]
I guess just cloning editorconfig-vim under `~/.vim/bundle` is enough with pathogen :)

So, the only thing missing are brief installation instructions in README.md (see [vim-coffee-script](https://github.com/kchmck/vim-coffee-script#install-using-pathogen) for example).
