### ISSUE TITLE
ftplugin overriding editorconfig

### ISSUE THREAD

**Issue by codeinabox** [editorconfig/editorconfig-vim#35]
I've noticed that if I have a ftplugin eg .vim/after/ftplugin/yaml.vim

```
setlocal expandtab
setlocal tabstop=2
setlocal shiftwidth=2
```
That this overrides what I have set in the .editorconfig

**Comment by xuhdev** [comment]
@codeinabox  I cannot reproduce this bug. Which OS do you use? Can you run `editorconfig $(pwd)/x.yml` and paste the output here?

**Comment by codeinabox** [comment]
It's working all fine for me now so I am going to close this bug
