### ISSUE TITLE
open the python file in the editorconfig-vim will cause problem

### ISSUE THREAD

**Issue by mirguest** [editorconfig/editorconfig-vim#37]
Hi! 

When open the file in the `editorconfig-vim/plugin/editorconfig-core-py`, following error is reported:
```
Failed to execute "python /home/ihep/.vim/bundle/editorconfig-vim/plugin/editorconfig-core-py/main.py/main.py '/home/ihep/.vim/bundle/editorconfig-vim/plugin/editorconfig-core-py/.editorconfig'". Exit code: 2
Message:
['python: can''t open file ''/home/ihep/.vim/bundle/editorconfig-vim/plugin/editorconfig-core-py/main.py/main.py'': [Errno 20] Not a directory']
```

I find the problem is caused in `s:FindPythonFiles`, which returns a wrong directory.
`findfile(g:EditorConfig_python_files_dir . '/main.py',','.&runtimepath)` will return `main.py`, so the substitution will be failed.

**Comment by xuhdev** [comment]
@mirguest I guess your `g:EditorConfig_core_mode` is `python_external`, right? I cannot really reproduce this bug, and `findfile(g:EditorConfig_python_files_dir . '/main.py',','.&runtimepath)` returns  `/home/hong/.vim/bundle/editorconfig-vim/plugin/editorconfig-core-py/main.py` for me, as the next substitution will replace out `main.py`, which is correct.

**Comment by mirguest** [comment]
@xuhdev Actually I don't set `g:EditorConfig_core_mode`. Following is my vim version info:
```
ihep@ihep:~/.vim/bundle> LANG=en_US.C vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10)
Included patches: 1-52
Compiled by 'http://www.opensuse.org/'
Huge version without GUI.  Features included (+) or not (-):
```
Because I found the `findfile` will return the relative path, so after I open a file ( `/home/ihep/.vim/bundle/editorconfig-vim/plugin/editorconfig-core-py/main.py`), only `mail.py` is returned.
My current fix is: `fnamemodify(l:python_core_files_dir, ':p:h')`. I add `:h` to remove the last component.

**Comment by xuhdev** [comment]
It's strange, as `findfile()` on my system returns full path. Did you see any option for `findfile()`? It's really strange.

**Comment by xuhdev** [comment]
Here's my viminfo:

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 31 2015 23:36:07)
Included patches: 1-488, 576
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by jamessan@debian.org
Huge version with GTK2 GUI.  Features included (+) or not (-): 
```

I didn't find any changes related to `findfile` in the Vim commit log.

**Comment by xuhdev** [comment]
What is the value of your `g:EditorConfig_core_mode`? You can check it by run `:echo g:EditorConfig_core_mode`.

**Comment by mirguest** [comment]
@xuhdev I don't set the `g:EditorConfig_core_mode` in my vimrc. Following is my test:
```!bash
> vim '+chdir ~/.vim/bundle/editorconfig-vim/plugin/editorconfig-core-py' '+execute "!echo ".findfile("plugin/editorconfig-core-py/main.py", &runtimepath)' +qall
main.py
> vim '+execute "!echo ".findfile("plugin/editorconfig-core-py/main.py", &runtimepath)' +qall
.vim/bundle/editorconfig-vim/plugin/editorconfig-core-py/main.py
```
The output is relative path if I change the current directory.

**Comment by xuhdev** [comment]
@mirguest The first line prints `/home/hong/.vim/bundle/editorconfig-vim/plugin/editorconfig-core-py/main.py` for me. Same result for the second line.

**Comment by mirguest** [comment]
@xuhdev I also try it in an old vim:
```
VIM - Vi IMproved 7.2 (2008 Aug 9, compiled Apr  5 2012 05:28:37)
Included patches: 1-411
```
The result:
```
$ vim '+chdir ~/.vim/bundle/editorconfig-vim/plugin/editorconfig-core-py' '+execute "!echo ".findfile("plugin/editorconfig-core-py/main.py", &runtimepath)' +qall
main.py
$ vim '+execute "!echo ".findfile("plugin/editorconfig-core-py/main.py", &runtimepath)' +qall
.vim/bundle/editorconfig-vim/plugin/editorconfig-core-py/main.py
```

**Comment by xuhdev** [comment]
My Vim version is later than yours

**Comment by travi** [comment]
I can confirm that I am seeing this same issue on 7.3 on a machine that cannot easily be updated to 7.4. on osx, where i do have 7.4 installed, i do not see this issue

**Comment by xuhdev** [comment]
I retested using the version the OP has, but I still have no problem (full path is printed). @mirguest  If it's OK, can you send your configuration file privately/publicly to me? I want to check whether there is an evil configuration.

**Comment by mirguest** [comment]
@xuhdev This is my vimrc: https://github.com/mirguest/vimrc-ihep/blob/master/vimrc .

**Comment by travi** [comment]
my `.vimrc` can be found here: https://github.com/travi/dotfiles/blob/master/vim/.vimrc

i use my dotfiles on multiple machines, including 2 macbooks running yosemite, a windows vm using gitbash, and several ubuntu vms. the problems I'm seeing are only in a qnap box that runs an embeded version of ubuntu. I've captured more details here: https://github.com/travi/dotfiles/issues/90#issuecomment-114726787

also, it only seems to occur when i'm opening a file directly. if i open vim directly with just `vim`, i do not see the error. when opening a file like `.bash_profile`, i see the error. i can dismiss the error and still continue into a working vim, but i would like the annoyance of the error to be removed and to ensure editorconfig is being applied correctly.

**Comment by xuhdev** [comment]
OK, I have confirmed that the OP's Vim behavior should be the expected Vim behavior. If you can make a pull request of the fix I'm gonna accept it (replace `substitute` with `fnamemodify`). Thanks!

**Comment by mirguest** [comment]
@xuhdev what does OP mean?

**Comment by xuhdev** [comment]
@mirguest Original Poster

**Comment by travi** [comment]
I dug in deeper and realized that I misspoke when I said that I was seeing the same problem. I am seeing similar symptoms, but my issue appears to be related to python version. 

The system where I see this problem is running python 2.7.5 without an easy way to upgrade it. It is failing to load `configparser` because it was called `ConfigParser` pre-python-3.

Would it be reasonable to support earlier versions of python with this plugin? If so, I would be happy to open a separate issue.

**Comment by xuhdev** [comment]
@mirguest I have to reconsider the PR as I seem to have mistakenly done thought something.
@travi I didn't find where `configparser` is used. Can you show me please?

**Comment by travi** [comment]
I'm not that strong with vim plugin development or python in general, but [here is the stacktrace](https://github.com/travi/dotfiles/issues/90#issuecomment-114726787) that I was seeing, which makes it look like the reference is [here](https://github.com/editorconfig/editorconfig-vim/blob/master/plugin/editorconfig-core-py/editorconfig/exceptions.py#L15)

**Comment by xuhdev** [comment]
@travi Your problem seems to be a different problem. Is `qnap` the only system you have problem with? I guess you didn't install the `ConfigParser` python library. Can you try to install the full version Python?

**Comment by travi** [comment]
Yeah, that's the only system where I'm seeing the error. It's a [TS-251](https://www.qnap.com/i/en/product/model.php?II=142) which is essentially just a NAS, so it's pretty stripped down. Even `apt` isn't available. 

I've been continuing to dig in and finally figured out that a `python3` package was available through `ipkg`. It wasn;t showing up when I was just searching for `python`. Anyway, I've got that installed and it seems like vim picked that up since syntax highlighting is working much better now.

However, I'm still seeing what appears to be the same error, but in color now. Do you know of a way that I can confirm if `configparser`/`ConfigParser` was included? If not, I'll keep digging.

**Comment by xuhdev** [comment]
you can run python on command line, then run 'import ConfigParser'

**Comment by travi** [comment]
great, thanks. the repl did make that simple to identify.

`ConfigParser` seems to be a problem:
```py
>>> import ConfigParser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named ConfigParser
```

but `configparser` appears to be available:
```py
>>> import configparser
>>> 
```

I did also confirm that neither are available in the python 2 install.

**Comment by travi** [comment]
further info. it appears that I may have been inconsistent in using `vi` and `vim`, which appear to actually be different on this system. Therefore, seeing sytax work more properly probably wasn't enough evidence to say that vim is using python3. It appears that it is still using python2.

**Comment by travi** [comment]
to stick to python 2, I went ahead and installed the version of python 2 that was available in `ipkg`. It's an older version, but I don't think I have a need for an up to date version on this system.

This did seem to fix the problem, so I think I'm good now. Thanks for the help and sorry for the noise in this thread.

**Comment by shivapoudel** [comment]
@xuhdev till now I am getting like this:
![capture](https://cloud.githubusercontent.com/assets/3774827/9704114/9138239a-54ba-11e5-8d4a-4d54954f8e3d.PNG)
