### ISSUE TITLE
Error detected while processing function <SNR>26_InitializePythonBuiltin:

### ISSUE THREAD

**Issue by MartinDelille** [editorconfig/editorconfig-vim#43]
I try to install this plugin via *Vundle* by adding the following line to my .vimrc:

    Plugin 'editorconfig/editorconfig-vim'

It triggers the following error:

    Error detected while processing function <SNR>26_InitializePythonBuiltin:
    line   23:
    E887: Sorry, this command is disabled, the Python's site module could not be loaded.
    line   44:
    E887: Sorry, this command is disabled, the Python's site module could not be loaded.
    Press ENTER or type command to continue

I tried to deactivate all my other plugin without success.

Any idea what is going wrong?

**Comment by xuhdev** [comment]
Can you post your output of `:version`?

**Comment by MartinDelille** [comment]
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 12 2014 17:06:14)
    MacOS X (unix) version
    Included patches: 1-488
    Compiled by Homebrew
    Huge version without GUI.  Features included (+) or not (-):
    +acl             +dialog_con      +insert_expand   +mouse_sgr       +ruby            +vertsplit
    +arabic          +diff            +jumplist        -mouse_sysmouse  +scrollbind      +virtualedit
    +autocmd         +digraphs        +keymap          +mouse_urxvt     +signs           +visual
    -balloon_eval    -dnd             +langmap         +mouse_xterm     +smartindent     +visualextra
    -browse          -ebcdic          +libcall         +multi_byte      -sniff           +viminfo
    ++builtin_terms  +emacs_tags      +linebreak       +multi_lang      +startuptime     +vreplace
    +byte_offset     +eval            +lispindent      -mzscheme        +statusline      +wildignore
    +cindent         +ex_extra        +listcmds        +netbeans_intg   -sun_workshop    +wildmenu
    -clientserver    +extra_search    +localmap        +path_extra      +syntax          +windows
    +clipboard       +farsi           -lua             +perl            +tag_binary      +writebackup
    +cmdline_compl   +file_in_path    +menu            +persistent_undo +tag_old_static  -X11
    +cmdline_hist    +find_in_path    +mksession       +postscript      -tag_any_white   -xfontset
    +cmdline_info    +float           +modify_fname    +printer         -tcl             -xim
    +comments        +folding         +mouse           +profile         +terminfo        -xsmp
    +conceal         -footer          -mouseshape      +python          +termresponse    -xterm_clipboard
    +cryptv          +fork()          +mouse_dec       -python3         +textobjects     -xterm_save
    +cscope          -gettext         -mouse_gpm       +quickfix        +title           -xpm
    +cursorbind      -hangul_input    -mouse_jsbterm   +reltime         -toolbar
    +cursorshape     +iconv           +mouse_netterm   +rightleft       +user_commands
       system vimrc file: "$VIM/vimrc"
         user vimrc file: "$HOME/.vimrc"
     2nd user vimrc file: "~/.vim/vimrc"
          user exrc file: "$HOME/.exrc"
      fall-back for $VIM: "/usr/local/share/vim"
    Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -Os -w -pipe -march=native
     -mmacosx-version-min=10.9 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
    Linking: /usr/bin/clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/lo
    cal/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib  -L/usr/local/lib -Wl,-h
    eaderpad_max_install_names -o vim        -lm  -lncurses -liconv -framework Cocoa   -fstack-protector -L
    /usr/local/lib  -L/System/Library/Perl/5.16/darwin-thread-multi-2level/CORE -lperl -framework Python
    -lruby.2.1.0 -lobjc -L/Users/martin/.rvm/rubies/ruby-2.1.2/lib

**Comment by xuhdev** [comment]
I think it might be due to your recent upgrade of Python. Since you've installed vim via homebrew, please run `brew reinstall vim` to link to the upgraded Python.

**Comment by MartinDelille** [comment]
Your right it's fixed now!
