### ISSUE TITLE
Cannot load config when `set shell=sh` on Windows

### ISSUE THREAD

**Issue by hail2u** [editorconfig/editorconfig-vim#44]
I use Windows GVim with `set shell=sh` (this `sh` comes from Git for Windows). With this environment, `editorconfig-vim` silently failed to load config files because this plugin changes `shellescape` for Command Prompt.

When I commented out [line 463, 464 and 466][1], `editorconfig-vim` works as expected.

I think `editorconfig-vim` should check `shell` not only `shellslash`. I know this environment is very rare, but I’m happy if you fix this problem.

[1]: https://github.com/editorconfig/editorconfig-vim/blob/912eeeab7d7702358904552b9940e12e2f0a9afd/plugin/editorconfig.vim#L463-L466

**Comment by xuhdev** [comment]
@hail2u Do you have a suggested solution? You are very welcome to make a PR, as I don't really have this environment to test

**Comment by hail2u** [comment]
OK. I've read Vundle code, and it seems checking `empty(matchstr(&shell, 'sh'))` is enough in this case.
