### ISSUE TITLE
Creating hook for when no config for current file type?

### ISSUE THREAD

**Issue by codeinabox** [editorconfig/editorconfig-vim#46]
Is it possible to create a hook to do something when there is no config for the current file type? Was wondering if I could invoke the [:DetectIndent command](https://github.com/ciaranm/detectindent) when this happens

**Comment by xuhdev** [comment]
You can create a hook function and test whether the passed in config is empty. Is this what you want?

**Comment by codeinabox** [comment]
Yes, how would I do that?

**Comment by xuhdev** [comment]
`:h editorconfig-hook`, and test the emptiness in the hook function.

**Comment by codeinabox** [comment]
My VimScript is not so good. How would I do this?
