### ISSUE TITLE
Slow startup time

### ISSUE THREAD

**Issue by af** [editorconfig/editorconfig-vim#50]
Hi,

I've been profiling my vim startup time, and have found that the editorconfig plugin is taking over half of the total startup time (150ms - 230ms, not including python initialization). I'm wondering if there's a known way to slim this down, either with configuration options or some other means.

Other notes
* I'm using a recent build of neovim
* slow startup time persists regardless of whether there's an `.editorconfig` file present in the dir

**Comment by xuhdev** [comment]
Can you try to adjust `g:EditorConfig_core_mode` to different values and see what happens?

**Comment by af** [comment]
Hi @xuhdev,

I added `let g:EditorConfig_core_mode = 'python_external'` and it made the plugin loading 3 orders of magnitude faster! Closing the issue now, but is there any downside to this setting?

**Comment by asgeo1** [comment]
:+1:  for `python_external` - has speed up my vim startup heaps :)

**Comment by asgeo1** [comment]
Actually, the external one is even faster again.  If on OSX:

    brew install editorconfig
   
    let g:EditorConfig_core_mode = 'external_command'

**Comment by xuhdev** [comment]
Great! How about writing it into the doc?

**Comment by toastal** [comment]
Even with trying different `EditorConfig_core_mode` (and exec_path) in nvim, it takes 8 seconds to startup vs <1s without.

**Comment by xuhdev** [comment]
@toastal Maybe neovim/neovim#2437 is the cause?

**Comment by toastal** [comment]
let g:python_host_skip_check = 1
let g:python3_host_skip_check = 1

let g:python_host_prog='/usr/local/bin/python2'
let g:python3_host_prog='/usr/local/bin/python3'

let g:EditorConfig_exec_path = '/usr/local/bin/editorconfig'
let g:EditorConfig_core_mode = 'external_command'
```

**Comment by xuhdev** [comment]
@toastal I really don't know why and I'm unable to test neovim at this moment. Have you communicated with the Neovim community? Maybe some of them have the same experience as you had.
