### ISSUE TITLE
A clearer installation procedure

### ISSUE THREAD

**Issue by pieplu** [editorconfig/editorconfig-vim#60]
Hi, 

Thanks for this plug-in. But it's hard to understand how to install it.

Can you improve the Install section on the README ?

Like: 

    Step1: Extract this files... on this folder
    Step2: Add this line... on this file

Thanks in advence

**Comment by hs0ucy** [comment]
+1

**Comment by ubik23** [comment]
+1

**Comment by xuhdev** [comment]
Can you explain which part you don't understand in the README? Maybe you missed the point that in the README, it really says "one of the following method". I agree that the word "archive" isn't clear.

**Comment by pieplu** [comment]
Hi!

Thanks, your right! I missed this point!

In most case, the list is used for steps. 
And we don't understand that is different way (our fault).

Maybe add title for each way (like Install with pathogen, Install with Vundle),
or use "OR" at the begining of each.

And for the word "archive", maybe it's can be good to explain the "final state" (folder/files).

Thanks :)
