### ISSUE TITLE
Not respecting indentation settings from .vimrc when no .editorconfig file present

### ISSUE THREAD

**Issue by joeattardi** [editorconfig/editorconfig-vim#61]
If I run vim inside a project that does have an `.editorconfig` file, it behaves as expected.

I'm on OSX running Vim 7.4.

But if I run vim somewhere else, where there is not an `.editorconfig` file, this plugin is changing my indentation settings.

From my .vimrc:

```
set tabstop=2
set shiftwidth=2
set softtabstop=2
```

But then if I, say, edit a .js file in a directory without an `.editorconfig` file, I get this:
```
set tabstop? ==> tabstop=4
set shiftwidth? ==> shiftwidth=4
set softtabstop? ==> softtabstop=4
```

**Comment by xuhdev** [comment]
Do you have an .editorconfig file in an upper dir?

**Comment by joeattardi** [comment]
Doh! That was the problem. I'm sorry, I should have read the docs more closely.
