### ISSUE TITLE
Wildcard in runtimepath breaks path escaping in plugin

### ISSUE THREAD

**Issue by mnebuerquo** [editorconfig/editorconfig-vim#63]
See issue https://github.com/vim/vim/issues/710 in vim for the whole story.

Changes made in 75fe572 added path escaping. I use a wildcard in my runtimepath:
```
set runtimepath+=~/.vim/bundle/*/
```

The wildcard in combination with the escaping causes `l:python_core_files_dir` to be empty. This prevents the plugin from finding `main.py`. The result is an error message appearing whenever I open a file: `Failed to execute "'python' '$PWD/main.py'"`

**Comment by xuhdev** [comment]
@grafi-tt What do you think would be a good fix?

**Comment by xuhdev** [comment]
Can you test again with the latest version? I've made some changes.

**Comment by mnebuerquo** [comment]
@xuhdev , your fix (d956329) appears to be working. I'll test again on the mac later tonight.

**Comment by silverwind** [comment]
Still seems to be an issue on `master` when a empty string is present in `wildignore`.

**Comment by xuhdev** [comment]
@silverwind Hmm, what issue did you see? I also didn't see any reason to set empty to `wildignore` actually, so maybe something should be done with Vim itself?

**Comment by silverwind** [comment]
A error like `Failed to execute "'python' '$PWD/main.py'"` would flash on every startup. It's a minor issue as the error message was not persistent, it was gone in about half a second.

Also not sure if that empty string pattern was actually serving a purpose, i got it from someone else's configuration and it may just have been a mistake there.

**Comment by xuhdev** [comment]
@silverwind I'll try to figure out the issue and probably report it to the Vim community.

**Comment by sahibalejandro** [comment]
Hello, this error still happening.
Any updates on this?

**Comment by xuhdev** [comment]
@sahibalejandro Can you describe the steps to reproduce this issue?

**Comment by sahibalejandro** [comment]
I just installed it using Plug.
It started working after I installed EditorConfig Core, I thought this won't be necessary because my vim installation has `+python/dyn`, I guess is not the same as just `+python`. ? 🤔

Well, it's working now, thanks for the quick response. 😀

**Comment by xuhdev** [comment]
@sahibalejandro `/dyn` means Vim may or may not load Python module depending on its availability. It could be the case that your Vim installation could not find the Python module :smile:

**Comment by sahibalejandro** [comment]
Oh, now it makes sense!
The weird thing is that I actually have python installed on my system, don't know why vim is not recognising it. 🤷🏻‍♂️
