### ISSUE TITLE
Vim 8 pack structure

### ISSUE THREAD

**Issue by tasmo** [editorconfig/editorconfig-vim#67]
Vim 8 can load plugins now natively. Like described in the [packages docs](https://vimhelp.appspot.com/repeat.txt.html#packages) it needs some well placed files to get recognized. Likewise:

> Your directory layout would be like this:
> 
> ``` vim
> start/foobar/plugin/foo.vim          " always loaded, defines commands
> start/foobar/plugin/bar.vim          " always loaded, defines commands
> start/foobar/autoload/foo.vim        " loaded when foo command used
> start/foobar/doc/foo.txt             " help for foo.vim
> start/foobar/doc/tags                " help tags
> opt/fooextra/plugin/extra.vim        " optional plugin, defines commands
> opt/fooextra/autoload/extra.vim      " loaded when extra command used
> opt/fooextra/doc/extra.txt           " help for extra.vim
> opt/fooextra/doc/tags                " help tags
> ```
> 
> This allows for the user to do: 
> 
> ``` shell
> mkdir ~/.vim/pack/myfoobar
> cd ~/.vim/pack/myfoobar
> git clone https://github.com/you/foobar.git
> ```

**Comment by xuhdev** [comment]
That's great! Would you like to make a pull request?

**Comment by tasmo** [comment]
I'll try to…

**Comment by k-takata** [comment]
My understanding is that use of `start/` or `opt/` is a user's choice, not plugin author's.
If a user always wants to load a plugin:

```
mkdir -p ~/.vim/pack/foobar/start
cd ~/.vim/pack/foobar/start
git clone https://github.com/editorconfig/editorconfig-vim.git
```

If a user wants to load a plugin on demand:

```
mkdir -p ~/.vim/pack/foobar/opt
cd ~/.vim/pack/foobar/opt
git clone https://github.com/editorconfig/editorconfig-vim.git
```

And when he want to load it, he should type:

```
:packadd editorconfig-vim
```

No need to change the current directory structure of editorconfig-vim.

**Comment by xuhdev** [comment]
I thought @tasmo meant to update the doc. Am I right?

**Comment by zakkudo** [comment]
I'm already using this with vim 8 with no changes. What's missing? Is this valid?

**Comment by sam-github** [comment]
Somewhat valid, the README should describe how use editorconfig-vim with Vim8: https://github.com/editorconfig/editorconfig-vim/pull/134
