### ISSUE TITLE
Error after upgrading Python (and pip)

### ISSUE THREAD

**Issue by rafaelrinaldi** [editorconfig/editorconfig-vim#69]
Just upgraded Python to `2.7.12` today and the plugin breaks. Basically when I try to do everything within Vim, I get the following error message:

```
Error detected while processing function <SNR>20_InitializePythonBuiltin:
line   23:
E887: Sorry, this command is disabled, the Python's site module could not be loaded.
Press ENTER or type command to continue
```

Had to remove the plugin in order to use Vim.

My setup:

```
$ python --version
Python 2.7.12

$ pip --version
pip 8.1.2 from /usr/local/lib/python2.7/site-packages (python 2.7)

$ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 26 2016 11:13:04)
MacOS X (unix) version
Included patches: 1-13
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     -gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
-clientserver    +insert_expand   +packages        -toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      -lua             +rightleft       +writebackup
+diff            +menu            +ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      -mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax
+farsi           +mouse_netterm   +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework Cocoa   -mmacosx-version-min=10.11 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.24.0_1/lib/perl5/5.24.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -F/usr/local/Cellar/python/2.7.12/Frameworks -framework Python   -lruby.2.3.0 -lobjc -L/usr/local/Cellar/ruby/2.3.1/lib
```

Both installed via Homebrew, by the way.

**Comment by xuhdev** [comment]
https://github.com/editorconfig/editorconfig/wiki/FAQ#when-using-the-vim-plugin-i-got-e887-sorry-this-command-is-disabled-the-pythons-site-module-could-not-be-loaded

**Comment by rafaelrinaldi** [comment]
@xuhdev Thanks for the reply. Already tried all the steps mentioned there, that's why I've reported the issue.

**Comment by xuhdev** [comment]
Does `:python print('a')` work on your system?

**Comment by rafaelrinaldi** [comment]
No. I get an error message:

```
E887: Sorry, this command is disabled, the Python's site module could not be loaded.
```

**Comment by xuhdev** [comment]
That's the issue you should try to solve... Honestly this is nothing caused by this plugin... If you run vim with `vim -nu NONE` and then run `:python print('a')` what happens? The `:python` command may be disabled if some part of other plugins call `:python3` first.

**Comment by rafaelrinaldi** [comment]
Same thing happens if I run in `vim -nu NONE` mode.

The weird thing is that this only happens if I have EditorConfig installed...

Any other ideas?

**Comment by rafaelrinaldi** [comment]
@xuhdev The same thing just happened with Ultisnips, so nevermind. If you happen to have any idea of why this is happening I would appreciate, but since it looks like there's nothing to do with EditorConfig itself, I'm closing the issue.

Thanks.

**Comment by xuhdev** [comment]
You can consider ask about it in the Vim mailing list: http://www.vim.org/community.php

**Comment by rafaelrinaldi** [comment]
FTR I've installed both `python` and `python3` through Homebrew and it fixed all the issues.

**Comment by kirillrogovoy** [comment]
Hi!

I recently ran into the same issue.
I fixed it by recompiling `vim` with a specific Homebrew flag:
```bash
brew install vim # wait for all dependencies to get installed
brew reinstall vim --with-custom-python # init a manual local compilation using local python
```

For more info run `brew info vim`.

I may want to add this to your FAQ: https://github.com/editorconfig/editorconfig/wiki/FAQ#when-using-the-vim-plugin-i-got-e887-sorry-this-command-is-disabled-the-pythons-site-module-could-not-be-loaded

**Comment by xuhdev** [comment]
@kirillrogovoy Thanks for the info. Is it fixed if `--with-custom-python` is missing?

**Comment by kirillrogovoy** [comment]
@xuhdev In my case, no. Problem persists as long as `brew` downloads pre-built binaries.

I have Sierra 10.12.2, btw.

**Comment by xuhdev** [comment]
@kirillrogovoy So there isn't really anything to update in the FAQ then :)

**Comment by kirillrogovoy** [comment]
@xuhdev Sorry, quite didn't get that.
I meant that you can mention that `--with-custom-python` flag in the FAQ, because it helps when a simple `brew reinstall vim` doesn't. :)

**Comment by xuhdev** [comment]
@kirillrogovoy Can you give an example of the updated text?

**Comment by kirillrogovoy** [comment]
@xuhdev 

Replace the text under [this](https://github.com/editorconfig/editorconfig/wiki/FAQ#when-using-the-vim-plugin-i-got-e887-sorry-this-command-is-disabled-the-pythons-site-module-could-not-be-loaded) header.

It is likely to happen on macOS with Vim and Python installed using Homebrew. It usually happens after a Python upgrade, which the old Vim installation does not recognize the new Python installation. To fix it, run `brew reinstall vim` or `brew reinstall macvim`. If it didn't help, try to recompile Vim locally running `brew reinstall vim --with-custom-python` or `brew reinstall macvim --with-custom-python`. For more info, check `brew info vim` / `brew info macvim`.

**Comment by xuhdev** [comment]
@kirillrogovoy Thanks, updated.
