### ISSUE TITLE
Doesn't respect single file definitions in case of multifile definitions

### ISSUE THREAD

**Issue by mstruebing** [editorconfig/editorconfig-vim#75]
The title is a bit misleading, what I mean is if I define editorconfig properties like `[*.{md}]` for example neovim isn't respect this rules.

If I add a second type like `[*.{md, yaml}]` for example it is working, also when I remove the curly braces like `[*.md]` it is working.

So I think this is a bug and should be fixed.

WDYT?

**Comment by xuhdev** [comment]
`[*.{md}]` means literally anything ending with `{md}`. Unless there is a comma inside the curly braces, the curly braces are treated as literal characters.

**Comment by mstruebing** [comment]
But that doesn't work for me, it is ignoring the rules in this case.

**Comment by xuhdev** [comment]
@mstruebing Can you clarify which rule is ignored? `[*.{md}]` won't match `README.md` and it is expected so. `[*.md]` should match.

**Comment by mstruebing** [comment]
Could you simply explain why `[*.{md}]` should not match `README.md`? - anything followed by a `.` and then `md` - in my point  of view it should match.

**Comment by xuhdev** [comment]
Only when a comma is inside the curly braces are considered to  be "alternative matching", meaning one of the items should be matched. Otherwise, `{}` are seen as literals.

You can also test this in bash: `a.md` won't match `a.{md}` but will match `a.{md,anything}`.
