### ISSUE TITLE
Installing EditorConfig Core in a path with spaces (e.g. the Windows default) breaks plugin

### ISSUE THREAD

**Issue by elyscape** [editorconfig/editorconfig-vim#77]
On 64-bit Windows, the default install path for EditorConfig Core is `C:\Program Files (x86)\editorconfig`, rendering the full path to the binary `C:\Program Files (x86)\editorconfig\bin\editorconfig.exe` (on 32-bit Windows, the ` (x86)` is removed). Unfortunately, if EditorConfig Core is installed in a path with a space (e.g. the aforementioned default) and Python is not, the following error occurs when trying to open a file:
```
"file.txt" 1L, 7C\editorconfig\bin\editorconfig was unexpected at this time.

Error detected while processing function <SNR>20_UseConfigFiles[20]..<SNR>20_UseConfigFiles_ExternalCommand[2]..<SNR>20_
SpawnExternalParser:
line   31:
E484: Can't open file C:\Users\elysc\AppData\Local\Temp\VIo4B54.tmp
Failed to execute "C:\Program Files (x86)\editorconfig\bin\editorconfig "C:\Users\elysc\Documents\file.txt"". Exit code:
 1
Message:
[]
```
Here's what's going on. The path to the EditorConfig Core binary is detected [from the searchlist][searchlist], and the value of (say) `C:\Program Files (x86)\editorconfig\bin\editorconfig` is set in `s:EditorConfig_exec_path`. Then, when it's time to execute the binary, `s:SpawnExternalParser()` [takes the and just appends filenames to it, executing the result][spawnexternalparser]. This results in it passing a value like `C:\Program Files (x86)\editorconfig\bin\editorconfig "C:\Users\elysc\Documents\file.txt"` to `system()`. Unfortunately, this then evaluates as:

- exec:
  - `C:\Program`
- args:
  - `Files`
  - `(x86)\editorconfig\bin\editorconfig`
  - `C:\Users\elysc\Documents\file.txt`

Which is obviously wrong and fails.

As an attempted workaround, I added this to my `.vimrc`:
```viml
let g:EditorConfig_exec_path = shellescape('C:\Program Files (x86)\editorconfig\bin\editorconfig')
```
Unfortunately, this doesn't work because the plugin (wisely) [runs it through `executable()`][executable] before using the value, and `executable()` requires the path you feed it to be unescaped.

A simple fix to this issue would be to wrap `s:EditorConfig_exec_path` in `shellscape()` [when feeding it to `s:SpawnExternalParser `][wraptarget].

[searchlist]: https://github.com/editorconfig/editorconfig-vim/blob/d956329/plugin/editorconfig.vim#L171-L185
[spawnexternalparser]: https://github.com/editorconfig/editorconfig-vim/blob/d956329/plugin/editorconfig.vim#L407-L438
[executable]: https://github.com/editorconfig/editorconfig-vim/blob/d956329/plugin/editorconfig.vim#L149
[wraptarget]: https://github.com/editorconfig/editorconfig-vim/blob/d956329/plugin/editorconfig.vim#L404

**Comment by elyscape** [comment]
As a side note, the command used when using an external Python command [is properly escaped][externalpython]. That being said, it will probably fail if `shellslash` is set, given that [the workaround described in `s:SpawnExternalParser()` is not applied there][shellslash]. That should probably be done in both `s:UseConfigFiles_Python_External()` and `s:UseConfigFiles_ExternalCommand()`.

[externalpython]: https://github.com/editorconfig/editorconfig-vim/blob/d956329/plugin/editorconfig.vim#L394-L395
[shellslash]: https://github.com/editorconfig/editorconfig-vim/blob/d956329/plugin/editorconfig.vim#L422-L429

**Comment by xuhdev** [comment]
@elyscape Thank you for your report. Unfortunately it's very difficult for me to access Windows. Can you try your fix and submit a PR?

**Comment by xuhdev** [comment]
@elyscape Oops, sorry didn't see your PR...
