### ISSUE TITLE
Error loading editorconfig

### ISSUE THREAD

**Issue by kevincox** [editorconfig/editorconfig-vim#80]
After a recent update editorconfig fails to load.

```
Error detected while processing function <SNR>21_FindPythonFiles:
line    3:
E117: Unknown function: <SNR>21_DisableShellSlash
line   18:
E117: Unknown function: <SNR>21_ResetShellSlash
```

cc: @elyscape

**Comment by kevincox** [comment]
I can confim that f62d9ed92f8616ad84753b499fe86e782471cc7c doesn't have this issue meaning that it was caused by #78.

**Comment by valtermro** [comment]
Having the exactly same problem.
I'm using neovim and have both python and python3 enabled.

**Comment by mikezaby** [comment]
Same problem with neovim

**Comment by jsatk** [comment]
Came here as I too am having the same issue.

**Comment by eirnym** [comment]
Have this problem too. I use `MacVim` 8.0 build 130 with `Python3` (only)

**Comment by eirnym** [comment]
Moving these functions to the beginning of the file solves the problem
