### ISSUE TITLE
how to set max line length in blog writing with markdown

### ISSUE THREAD

**Issue by 3xp10it** [editorconfig/editorconfig-vim#86]
Hello,I want to use markdown in blog writing,but my blog will change best line length with different size of computer screen size(I used bootstrap).How to set max line length in blog writing with markdown in editorconfig-vim?
When I set textwidth=111 in my .vimrc file,I find myself reading my blog good,but when I change to a smaller size pc,I find my blog looks bad coz line length should not be 111 any more.

Can you help me ?(my blog link:https://3xp10it.cc).Thx.

**Comment by xuhdev** [comment]
editorconfig-vim is for managing the code style of your markdown files themselves, not the HTML files generated from markdown files -- for whatever the HTML files should look like, you should consult the syntax of markdown, not for tools that help editing markdown files. I hope I'm understanding your question correctly.
