### ISSUE TITLE
trim_trailing_whitespace removes spaces in c++11 raw string literals

### ISSUE THREAD

**Issue by JonnyH** [editorconfig/editorconfig-vim#87]
Code like the following:

```
std::string test = R"(space 
here)";
```

I would argue that the expected contents of the variable should be "space \nhere"

But currently any whitespace after the word "space" is deleted, changing the contents of the "test" variable.

I don't know what the intended editorconfig behaviour is here, of if it's just an interaction with c++11 specific expectations that can never be 'solved'

**Comment by xuhdev** [comment]
Unfortunately, this is too specific to the language itself, which requires a parser for the whole language. I would suggest you to disable this feature for cpp files.
