### ISSUE TITLE
Plugin should strip CR characters from output of editorconfig-core

### ISSUE THREAD

**Issue by MikeRalphson** [editorconfig/editorconfig-vim#92]
I have a slightly unusual set up: I'm running Vim from Git-for-windows, with the windows build of editorconfig-core installed. I don't have a Python install currently.

When I set 

> let g:EditorConfig_verbose = 1

I see that the output of editorconfig.exe is garbled, presumably by the CRLF line endings. This leads to incorrect editor settings being applied.

As a workaround, I have a script which pipes the output of editorconfig.exe through `dos2unix` which seems to resolve the problem.

**Comment by xuhdev** [comment]
This unfortunately has to be changed on configuration of your system. The reason is that the Windows build editorconfig should never expect a UNIX-like environment. I think the way to fix it is to update `PATH` in your "git for Windows" env.

**Comment by MikeRalphson** [comment]
How would updating the `PATH` help? Unless there is a mingw build of editorconfig-core?

**Comment by xuhdev** [comment]
Yes, you have to rebuild it for your POSIX env, or disable it totally. The mixed use of these two envs are not supported (by most other programs as well).

**Comment by MikeRalphson** [comment]
Understood. But it is a little disappointing when the fix is relatively simple to implement...

**Comment by xuhdev** [comment]
@MikeRalphson What is the simple fix you have in mind? If it is easy to incorporate, I don't minding doing so. If it is harder, we can put the workaround in the wiki page.

**Comment by xuhdev** [comment]
It turns out that the solution is pretty simple within the plugin code. I made another push to try to fix this issue, but unfortunately I don't have a way to test. Please try out the latest version. Thanks!

**Comment by MikeRalphson** [comment]
Many thanks @xuhdev that fixes it for me.
