### ISSUE TITLE
Doesn't seem to be working on Linux Mint 18 with `+python3`?

### ISSUE THREAD

**Issue by jonbri** [editorconfig/editorconfig-vim#93]
OS: Linux Mint 18
Vim: 7.4
`:ver` gives `-python` and `+python3`

I installed via pathogen by simply cloning this project into `~/.vim/bundle`. It seems to recognize the plugin because I can access the help files with `:help editorconfig.txt`.

I installed the editorconfig core with `apt install editorconfig`.

When I open Vim, with my `pwd` at the root of my project, I have this in `.editorconfig`:
```
root = true

[*]
indent_style = space
indent_size = 4
end_of_line = lf
charset = utf-8
```

But, when I create a file in the same directory (`play.js`) nothing seems to happen when I do something like:
```
if (true) {
   console.log('hi'); // only 3 spaces
}
```

Should editorconfig edit my buffer when I save so change the 3 spaces to 4 spaces?

**Comment by xuhdev** [comment]
Please see the [faq](https://github.com/editorconfig/editorconfig/wiki/FAQ#my-files-are-not-automatically-reformatted-the-editorconfig-plugin-is-not-working): EditorConfig is not supposed to reformat your existing contents.
