### ISSUE TITLE
Pollutes vim's search history

### ISSUE THREAD

**Issue by rosshadden** [editorconfig/editorconfig-vim#94]
When this plugin is enabled, doing a simple `:w<cr>` adds two entries to neovim's search history:

```
/\s\+$
/[\u0009\u0020\u00a0\u1680\u180e\u2000-\u200b\u202f\u205f\u3000\ufeff]\+$
```

The result is that after saving a file, hitting `n` for example to view the next occurrence of a pattern will instead search for `\s\+$`, which is not found.  I suspect based on the pattern this is related to trimming trailing whitespace.

I have had this plugin commented out for about a year and forgot why until I tried it again just now :D.  Should be an easy fix though, and I regret not bringing it up back then.

**Comment by k-takata** [comment]
`:keeppatterns` might be used for fixing this, it was introduced by Vim 7.4.083.

**Comment by cxw42** [comment]
@rosshadden Are you still experiencing this issue?  Have you experimented with `:keeppatterns`?

**Comment by sroccaserra** [comment]
I looked at editorconfig.vim, and it looks like there is only one place where a search is used (in fact a substitution), and the `keeppatterns` option is present (along with `winsaveview()` a few line above):

- <https://github.com/editorconfig/editorconfig-vim/blob/f305bc7/plugin/editorconfig.vim#L510>

**Comment by rosshadden** [comment]
No it doesn't do it anymore. I'm not sure whether I should close the issue though because it seems like it may be affecting @sroccaserra now?
