### ISSUE TITLE
Only first pattern is recognized in list

### ISSUE THREAD

**Issue by akrejczinger** [editorconfig/editorconfig-vim#95]
An example from a config I found somewhere on the internet:
```
# Windows junk
[{*.cmd, *.bat, *.reg, *.ps1, *.vbs, *.cs, *.fs, *.fsx, *.ahk}]
end_of_line = crlf
```

With this config if I open a .cmd file, the file format is correctly set to `utf-8[dos]`. But if I try to open a .bat file, the configuration has no effect and I get `utf-8[unix]`.
This also applies to the other config variables, only the first file pattern is recognized.

**Comment by xuhdev** [comment]
Your regex is not correct: No space should be after commas.
